### ISSUE TITLE
React component implementation

### ISSUE THREAD

**Issue by Studio384** [sippy-platform/mellow-css#36]
This is an umbrella issue to cover the implementation of the Mellow CSS components as React components. Mellow UI will be built on top of React 18 and use [Radix](https://www.radix-ui.com/) when there is need for it (the grid component won't need it, for example).

## Components
- [x] #50 Grid & Container
- [x] #49 Buttons
- [x] #62 Cards
- [x] #61 List
- [x] Input
  - [x] #53 Checkbox
  - [x] #54 Labels
  - [x] #55 Radio and Radio Group
  - [x] #56 Text and textarea
  - [x] #57 Slider
  - [x] #58 Select
- [ ] Pagination
- [ ] Offcanvas
- [ ] Navs and navbars
- [x] #52 Progress
- [x] #63 Alerts
- [x] #60 Label
- [x] #59 Dialog
