### ISSUE TITLE
CSS implementation

### ISSUE THREAD

**Issue by Studio384** [sippy-platform/mellow-css#7]
This is an overview issue for the implementation of the various utilities and components from the Figma Mellow UI-document in Mellow CSS.

## Atoms
- [x] #13 Colors
  - [x] #37 Color v2
  - [x] #43 Color v3 #45
    - [x] #46 Color v3 Dynamic themes
- [x] #10 Typography
  - [x] #42 RFS v2 #47
- [x] #13 Elevation
  - [x] #31 Utilities API #32
  - [x] #33 Utilities, part 2
- [x] #39 Code

## Components
- [x] #9 Grid & Container
- [x] #14 Buttons
- [x] #17 Cards
- [x] #18 List
- [x] #20 Input
  - [x] Text input & textarea
  - [x] Select input
  - [x] Checkbox
  - [x] Radio
  - [x] File
- [x] #23 Pagination
  - [x] #24 Pagination design refresh (pagination was a quick implementation for Sippy.cloud and as a result isn't styled properly)
- [x] #25 Offcanvas
- [x] #27 Navs and navbars
- [x] #28 Progress
- [x] #29 Alerts
  - [x] #30 Toast, use Alert as basis?
- [x] #35 Label
- [x] #38 Tables
- [x] #40 Breadcrumb
- [x] #41 Dropdown
- [x] #44 Modal
